spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/springboot_demo
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:123456}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml