ROSTemplateFormatVersion: '2015-09-01'
Description: ROS Nested Stack resource example
Resources:
  Stack:
    Type: ALIYUN::ROS::Stack
    Properties:
      TemplateBody:
        ROSTemplateFormatVersion: '2015-09-01'
      TimeoutMins: 5
