ROSTemplateFormatVersion: '2015-09-01'
Description: Test ACM Namespace、Configuration
Parameters:
  Name:
    Type: String
    Default: mytest
  DataId:
    Type: String
    Default: mytest
  Content:
    Type: String
    Default: key=Hello;value=World
  Type:
    Type: String
    Default: text
Resources:
  Namespace:
    Type: ALIYUN::ACM::Namespace
    Properties:
      Name:
        Ref: Name
  Configuration:
    Type: ALIYUN::ACM::Configuration
    Properties:
      DataId:
        Ref: DataId
      Content:
        Ref: Content
      Type:
        Ref: Type
      NamespaceId:
        Ref: Namespace
      Desc: Test Create Configuration
Outputs:
  DataId:
    Value:
      Fn::GetAtt:
      - Configuration
      - DataId
  Group:
    Value:
      Fn::GetAtt:
      - Configuration
      - Group
  CfgNamespaceId:
    Value:
      Fn::GetAtt:
      - Configuration
      - NamespaceId
  NamespaceId:
    Value:
      Fn::GetAtt:
      - Namespace
      - NamespaceId
