ROSTemplateFormatVersion: '2015-09-01'
Description: ECS DeploymentSet resource example
Parameters:
  DeploymentSetName:
    Type: String
    Default: mytest
  OnUnableToRedeployFailedInstance:
    Type: String
    Default: KeepStopped
Resources:
  DeploymentSet:
    Type: ALIYUN::ECS::DeploymentSet
    Properties:
      DeploymentSetName:
        Ref: DeploymentSetName
      OnUnableToRedeployFailedInstance:
        Ref: OnUnableToRedeployFailedInstance
Outputs:
  DeploymentSetId:
    Value:
      Fn::GetAtt:
      - DeploymentSet
      - DeploymentSetId
