ROSTemplateFormatVersion: '2015-09-01'
Description: Test ECS SecurityGroupIngress
Parameters:
  SecurityGroupId:
    Type: String
    Description: SecurityGroup Id
  SourceCidrIp:
    Type: String
    Description: SourceCidr Ip
Resources:
  SgIngress:
    Type: ALIYUN::ECS::SecurityGroupIngress
    Properties:
      SecurityGroupId:
        Ref: SecurityGroupId
      IpProtocol: all
      PortRange: -1/-1
      NicType: intranet
      SourceCidrIp:
        Ref: SourceCidrIp
