ROSTemplateFormatVersion: '2015-09-01'
Description: Test ECS DeploymentSet
Parameters:
  DeploymentSetName:
    Default: mytest
    Type: String
  OnUnableToRedeployFailedInstance:
    Default: KeepStopped
    Type: String
Resources:
  DeploymentSet:
    Properties:
      DeploymentSetName:
        Ref: DeploymentSetName
      OnUnableToRedeployFailedInstance:
        Ref: OnUnableToRedeployFailedInstance
    Type: ALIYUN::ECS::DeploymentSet
Outputs:
  DeploymentSetId:
    Value:
      Fn::GetAtt:
      - DeploymentSet
      - DeploymentSetId
