ROSTemplateFormatVersion: '2015-09-01'
Description: Test ECS SecurityGroupIngress
Parameters:
  SecurityGroupId:
    Description: SecurityGroup Id
    Type: String
  SourceCidrIp:
    Description: SourceCidr Ip
    Type: String
Resources:
  SgIngress:
    Properties:
      IpProtocol: all
      NicType: intranet
      PortRange: -1/-1
      SecurityGroupId:
        Ref: SecurityGroupId
      SourceCidrIp:
        Ref: SourceCidrIp
    Type: ALIYUN::ECS::SecurityGroupIngress
