ROSTemplateFormatVersion: '2015-09-01'
Description: Test ACM Namespace、Configuration
Parameters:
  Content:
    Default: key=Hello;value=World
    Type: String
  DataId:
    Default: mytest
    Type: String
  Name:
    Default: mytest
    Type: String
  Type:
    Default: text
    Type: String
Resources:
  Configuration:
    Properties:
      Content:
        Ref: Content
      DataId:
        Ref: DataId
      Desc: Test Create Configuration
      NamespaceId:
        Ref: Namespace
      Type:
        Ref: Type
    Type: ALIYUN::ACM::Configuration
  Namespace:
    Properties:
      Name:
        Ref: Name
    Type: ALIYUN::ACM::Namespace
Outputs:
  CfgNamespaceId:
    Value:
      Fn::GetAtt:
      - Configuration
      - NamespaceId
  DataId:
    Value:
      Fn::GetAtt:
      - Configuration
      - DataId
  Group:
    Value:
      Fn::GetAtt:
      - Configuration
      - Group
  NamespaceId:
    Value:
      Fn::GetAtt:
      - Namespace
      - NamespaceId
