ROSTemplateFormatVersion: '2015-09-01'
Description: Test Waf DomainConfig、AclRule、WafSwitch
Parameters:
  Domain:
    Description: Domain name.
    Type: String
  InstanceId:
    Description: WAF instance ID. Description Interface You can view your current
      WAF instance ID by calling DescribePayInfo.
    Type: String
  Protocols:
    Default: http
    Description: 'The domain supports access protocols, values: http: expressed support
      for the HTTP protocol. https: support for HTTPS protocol. http, https: supports
      HTTP, HTTPS protocol.'
    Type: String
  Region:
    Default: cn
    Type: String
  Rules:
    Default: '{"conditions":[{"key":"URL","contain":1,"value":"asfas"}],"continueComponent":{"post_action_cc":1,"post_action_waf":1,"post_action_sa":1,"post_action_block_geo":"0","post_action_data_risk_control":"1"},"action":"1","name":"test"}'
    Type: String
  ServiceOn:
    Default: 1
    Type: Number
Resources:
  AclRule:
    DependsOn: WafSwitch
    Properties:
      Domain:
        Ref: Domain
      InstanceId:
        Ref: InstanceId
      Region:
        Ref: Region
      Rules:
        Ref: Rules
    Type: ALIYUN::WAF::AclRule
  DomainConfig:
    Properties:
      Domain:
        Ref: Domain
      HttpPort: '["80"]'
      InstanceId:
        Ref: InstanceId
      IsAccessProduct: 0
      Protocols:
        Ref: Protocols
      SourceIps: '["1.1.1.1"]'
    Type: ALIYUN::WAF::DomainConfig
  WafSwitch:
    DependsOn: DomainConfig
    Properties:
      Domain:
        Ref: Domain
      InstanceId:
        Ref: InstanceId
      Region:
        Ref: Region
      ServiceOn:
        Ref: ServiceOn
    Type: ALIYUN::WAF::WafSwitch
Outputs:
  Cname:
    Description: CNAME assigned by WAF instance.
    Value:
      Fn::GetAtt:
      - DomainConfig
      - Cname
  ProtocolType:
    Description: 'agreement type:0: indicates that the HTTP protocol is supported.1:
      indicates that the HTTPS protocol is supported.2: indicates that both HTTP and
      HTTPS protocols are supported.'
    Value:
      Fn::GetAtt:
      - DomainConfig
      - ProtocolType
