ROSTemplateFormatVersion: '2015-09-01'
Description: Create ApiGateway VpcAccessConfig
Parameters:
  VpcId:
    Type: String
  Name:
    Type: String
  Port:
    Type: Number
    Default: 8080
  VSwitchId:
    Type: String
    Description: VSW Id.
  SecurityGroupId:
    Type: String
    Description: Security Group Id.
  ImageId:
    Type: String
    Label: ECS Image Id
    Default: centos_7
  InstanceType:
    Type: String
    Label: ECS Instance Type
    Default: ecs.c5.large
  SystemDiskCategory:
    Type: String
    Description: Category of system disk. Default is cloud_efficiency. support cloud|cloud_efficiency|cloud_ssd|cloud_essd|ephemeral_ssd.Old
      instances will not be changed.
    Default: cloud_essd
    AllowedValues:
    - cloud
    - cloud_efficiency
    - cloud_ssd
    - cloud_essd
    - ephemeral_ssd
  LoginPassword:
    Type: String
    Description: ECS Login Password
    Default: Admin123
    MinLength: 8
    MaxLength: 41
    NoEcho: true
Resources:
  ECS:
    Type: ALIYUN::ECS::Instance
    Properties:
      VpcId:
        Ref: VpcId
      VSwitchId:
        Ref: VSwitchId
      SecurityGroupId:
        Ref: SecurityGroupId
      ImageId:
        Ref: ImageId
      IoOptimized: optimized
      AllocatePublicIP: true
      InstanceType:
        Ref: InstanceType
      SystemDiskCategory:
        Ref: SystemDiskCategory
      Password:
        Ref: LoginPassword
  VpcAccessConfig:
    Type: ALIYUN::ApiGateway::VpcAccessConfig
    Properties:
      VpcId:
        Ref: VpcId
      InstanceId:
        Ref: ECS
      Name:
        Ref: Name
      Port:
        Ref: Port
    DependsOn: ECS
