ROSTemplateFormatVersion: '2015-09-01'
Description: Test ApiGateway StageConfig
Parameters:
  GroupName:
    Default: mytest
    Type: String
  Variables:
    Default:
      key: value
    Type: Json
Resources:
  Group:
    Properties:
      GroupName:
        Ref: GroupName
      InstanceId: api-shared-vpc-001
    Type: ALIYUN::ApiGateway::Group
  StageConfig:
    Properties:
      GroupId:
        Ref: Group
      StageName: TEST
      Variables:
        Ref: Variables
    Type: ALIYUN::ApiGateway::StageConfig
