ROSTemplateFormatVersion: '2015-09-01'
Description: Create ApiGateway VpcAccessConfig
Parameters:
  ImageId:
    Default: centos_7
    Label: ECS Image Id
    Type: String
  InstanceType:
    Default: ecs.c5.large
    Label: ECS Instance Type
    Type: String
  LoginPassword:
    Description: ECS Login Password
    MaxLength: 41
    MinLength: 8
    NoEcho: true
    Type: String
  Name:
    Type: String
  Port:
    Default: 8080
    Type: Number
  SecurityGroupId:
    Description: Security Group Id.
    Type: String
  VSwitchId:
    Type: String
  VpcId:
    Type: String
Resources:
  ECS:
    Properties:
      AllocatePublicIP: true
      ImageId:
        Ref: ImageId
      InstanceType:
        Ref: InstanceType
      IoOptimized: optimized
      Password:
        Ref: LoginPassword
      SecurityGroupId:
        Ref: SecurityGroupId
      SystemDiskCategory: cloud_efficiency
      VSwitchId:
        Ref: VSwitchId
      VpcId:
        Ref: VpcId
    Type: ALIYUN::ECS::Instance
  VpcAccessConfig:
    DependsOn: ECS
    Properties:
      InstanceId:
        Ref: ECS
      Name:
        Ref: Name
      Port:
        Ref: Port
      VpcId:
        Ref: VpcId
    Type: ALIYUN::ApiGateway::VpcAccessConfig
